services:
   _defaults:
      autowire: true
      autoconfigure: true
      public: true

   Jar\Utilities\:
      resource: '../Classes/*'
      exclude: '../Classes/Event/*'
  
   Jar\Utilities\Hooks\TCEmainHook:
      public: true

   Jar\Utilities\Services\FrontendTypoScriptAccessor:
    public: true
    autowire: true
    autoconfigure: true